### ISSUE TITLE
[BUG] Amethyst crash on fresh install after commit "Faster logout processing without..."

### ISSUE THREAD

**Issue by davotoula** [vitorpamplona/amethyst#1130]
Following commit https://github.com/vitorpamplona/amethyst/commit/67ea0dcf7fd791d970eaeb64b248d06ea2a587e3 the app crashes on start when no accounts are present.

No issue observed when account(s) already exist

Error:
`13:44:12.882  E  FATAL EXCEPTION: DefaultDispatcher-worker-3 (Ask Gemini)
                 Process: com.vitorpamplona.amethyst.debug, PID: 4510
                 java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "kotlinx.atomicfu.AtomicRef" on path: DexPathList[[zip file "/data/app/~~ohWb-1BBUFdFRNDfWjCJmg==/com.vitorpamplona.amethyst.debug-8H1f6eu2vaa5USLUncy2CQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~ohWb-1BBUFdFRNDfWjCJmg==/com.vitorpamplona.amethyst.debug-8H1f6eu2vaa5USLUncy2CQ==/lib/arm64, /data/app/~~ohWb-1BBUFdFRNDfWjCJmg==/com.vitorpamplona.amethyst.debug-8H1f6eu2vaa5USLUncy2CQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                 	at com.fasterxml.jackson.databind.util.ClassUtil.closeOnFailAndThrowAsIOE(ClassUtil.java:501)
                 	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4801)
                 	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040)
                 	at com.vitorpamplona.amethyst.LocalPreferences$savedAccounts$2.invokeSuspend(LocalPreferences.kt:185)
                 	at com.vitorpamplona.amethyst.LocalPreferences$savedAccounts$2.invoke(Unknown Source:8)
                 	at com.vitorpamplona.amethyst.LocalPreferences$savedAccounts$2.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
                 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                 	at com.vitorpamplona.amethyst.LocalPreferences.savedAccounts(LocalPreferences.kt:161)
                 	at com.vitorpamplona.amethyst.LocalPreferences.allSavedAccounts(LocalPreferences.kt:293)
                 	at com.vitorpamplona.amethyst.ui.MainActivity$onResume$2.invokeSuspend(MainActivity.kt:127)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d5b6bcd, Dispatchers.IO]
                 Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.atomicfu.AtomicRef" on path: DexPathList[[zip file "/data/app/~~ohWb-1BBUFdFRNDfWjCJmg==/com.vitorpamplona.amethyst.debug-8H1f6eu2vaa5USLUncy2CQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~ohWb-1BBUFdFRNDfWjCJmg==/com.vitorpamplona.amethyst.debug-8H1f6eu2vaa5USLUncy2CQ==/lib/arm64, /data/app/~~ohWb-1BBUFdFRNDfWjCJmg==/com.vitorpamplona.amethyst.debug-8H1f6eu2vaa5USLUncy2CQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
                 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.parseType(KDeclarationContainerImpl.kt:273)
                 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.loadReturnType(KDeclarationContainerImpl.kt:288)
                 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findMethodBySignature(KDeclarationContainerImpl.kt:198)
                 	at kotlin.reflect.jvm.internal.KPropertyImplKt.computeCallerForAccessor(KPropertyImpl.kt:311)
                 	at kotlin.reflect.jvm.internal.KPropertyImplKt.access$computeCallerForAccessor(KPropertyImpl.kt:1)
                 	at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke(KPropertyImpl.kt:179)
                 	at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke(KPropertyImpl.kt:178)
13:44:12.883  E  	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63) (Ask Gemini)
                 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
                 	at kotlin.reflect.jvm.internal.KPropertyImpl$Getter.getCaller(KPropertyImpl.kt:178)
                 	at kotlin.reflect.jvm.ReflectJvmMapping.getJavaMethod(ReflectJvmMapping.kt:63)
                 	at kotlin.reflect.jvm.ReflectJvmMapping.getJavaGetter(ReflectJvmMapping.kt:48)
                 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.getRequiredMarkerFromCorrespondingAccessor(KotlinAnnotationIntrospector.kt:138)
                 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:133)
                 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.access$hasRequiredMarker(KotlinAnnotationIntrospector.kt:27)
                 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector$hasRequiredMarker$hasRequired$1.invoke(KotlinAnnotationIntrospector.kt:47)
                 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector$hasRequiredMarker$hasRequired$1.invoke(KotlinAnnotationIntrospector.kt:40)
                 	at com.fasterxml.jackson.module.kotlin.ReflectionCache.javaMemberIsRequired(ReflectionCache.kt:110)
                 	at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:40)
                 	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.hasRequiredMarker(AnnotationIntrospectorPair.java:310)
                 	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.hasRequiredMarker(AnnotationIntrospectorPair.java:310)
                 	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getMetadata(POJOPropertyBuilder.java:227)
                 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._anyIndexed(POJOPropertiesCollector.java:1376)
                 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._sortProperties(POJOPropertiesCollector.java:1278)
                 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:529)
                 	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:294)
                 	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
                 	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:393)
                 	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:225)
                 	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
                 	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1525)
                 	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1473)
                 	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:578)
                 	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:856)
                 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:330)
                 	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799)
                 	... 18 more`

**Comment by davotoula** [comment]
verified!
