### ISSUE TITLE
[BUG] Exception when opening configuration of "Media Servers"

### ISSUE THREAD

**Issue by GitKalle** [vitorpamplona/amethyst#1186]
**Describe the bug**
When I try to open the configuration of the "Media Servers" the application crashes. But this just happens on one of my three accounts.

**To Reproduce**
1. Open Amethyst
2. Use the relevant account
3. Select "Media Servers" in the sidebar

**Expected behavior**
The configuration of Media Servers opens.

**Output of logcat**
```
11-22 08:56:12.299 16484 16484 E AndroidRuntime: FATAL EXCEPTION: main
11-22 08:56:12.299 16484 16484 E AndroidRuntime: Process: com.vitorpamplona.amethyst, PID: 16484
11-22 08:56:12.299 16484 16484 E AndroidRuntime: java.lang.IllegalArgumentException: Key "https://nostr.build" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SourceFile:23)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:2)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:35)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw(Unknown Source:14)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(Unknown Source:8)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-x0Ok8Vo(Unknown Source:331)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(Unknown Source:516)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:8)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke-0kLqBqw(Unknown Source:13)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(Unknown Source:8)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:112)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:72)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:0)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:37)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(SourceFile:2)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(SourceFile:1)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Unknown Source:129)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:45)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:93)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(Unknown Source:16)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(Unknown Source:39)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(Unknown Source:0)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:145)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:19)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(Unknown Source:10)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:9)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:105)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded$default(Unknown Source:11)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(Unknown Source:95)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(Unknown Source:32)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.node.Owner.measureAndLayout$default(Unknown Source:7)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.semanticsChangeChecker$lambda$49(Unknown Source:10)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.$r8$lambda$jwi4XcU60P00WX-z5TzcMCOc1u4(Unknown Source:0)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView$$ExternalSyntheticLambda4.run(Unknown Source:9)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:959)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8744)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:50)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-22 08:56:12.299 16484 16484 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
11-22 08:56:12.308 16484 16484 I Process : Sending signal. PID: 16484 SIG: 9
```

**Device:**
 - Phone Brand/Model: Pixel 6a
 - Android Version: Android 15 (GrapheneOS)
 - App Version: v0.92.7
 - Amber Version: v2.0.8

**Comment by davotoula** [comment]
I can reproduce this if I add https://nostr.build both as a nip96 server and a Blossom server
