### ISSUE TITLE
app freeze report

### ISSUE THREAD

**Issue by jlopp** [vitorpamplona/amethyst#119]
Not sure if this stack trace will help, but I experienced a freeze on GrapheneOS

```
type: ANR
osVersion: google/raven/raven:13/TQ1A.230205.002/2023021000:user/release-keys
package: com.vitorpamplona.amethyst:43
process: com.vitorpamplona.amethyst

activity: com.vitorpamplona.amethyst/.ui.MainActivity
cause: ANR Input dispatching timed out (f8e8402 com.vitorpamplona.amethyst/com.vitorpamplona.amethyst.ui.MainActivity (server) is not responding. Waited 5004ms for MotionEvent)
info: ANR in com.vitorpamplona.amethyst (com.vitorpamplona.amethyst/.ui.MainActivity)
PID: 30797
Reason: Input dispatching timed out (f8e8402 com.vitorpamplona.amethyst/com.vitorpamplona.amethyst.ui.MainActivity (server) is not responding. Waited 5004ms for MotionEvent)
Parent: com.vitorpamplona.amethyst/.ui.MainActivity
ErrorId: b5509544-3b64-4a6c-a7e8-090c84d446f1
Frozen: false
Load: 3.75 / 3.23 / 3.01
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.00 avg300=0.00 total=17977567
full avg10=0.00 avg60=0.00 avg300=0.00 total=6700038
----- End output from /proc/pressure/memory -----

CPU usage from 0ms to 18361ms later (2023-02-13 10:46:56.945 to 2023-02-13 10:47:15.306):
  158% 13161/org.telegram.messenger: 65% user + 93% kernel / faults: 164072 minor 137 major
  105% 30797/com.vitorpamplona.amethyst: 87% user + 18% kernel / faults: 1460836 minor 537 major
  12% 1512/system_server: 7.3% user + 5.2% kernel / faults: 45269 minor 433 major
  9.5% 28701/com.Slack: 6.9% user + 2.6% kernel / faults: 19963 minor 465 major
  7.5% 29459/com.google.android.inputmethod.latin: 5.1% user + 2.3% kernel / faults: 18781 minor 160 major
  6.5% 1976/com.android.systemui: 4.4% user + 2.1% kernel / faults: 36282 minor 199 major
  0% 1156/media.swcodec: 0% user + 0% kernel / faults: 6565 minor 28 major
  1.1% 521/sugov:0: 0% user + 1.1% kernel
  0.3% 3542/com.android.nfc: 0.2% user + 0.1% kernel / faults: 3451 minor 1447 major
  0.7% 555/surfaceflinger: 0.1% user + 0.6% kernel / faults: 2046 minor 5 major
  0.7% 29991/com.twitter.android: 0.3% user + 0.3% kernel / faults: 165 minor 9 major
  0.2% 2161/com.shannon.qualifiednetworksservice: 0% user + 0.1% kernel / faults: 2226 minor 1420 major
  0.6% 20209/.ShannonImsService: 0.3% user + 0.3% kernel / faults: 1856 minor 1233 major
  0% 1098/media.extractor: 0% user + 0% kernel / faults: 3390 minor 35 major
  0.5% 2329/com.shannon.imsservice: 0.2% user + 0.3% kernel / faults: 2197 minor 1297 major
  0.5% 2377/com.android.phone: 0.2% user + 0.2% kernel / faults: 2010 minor 817 major
  0% 2241/com.google.pixel.digitalkey.timesync: 0% user + 0% kernel / faults: 2010 minor 2231 major
  0.4% 2311/com.shannon.rcsservice: 0.2% user + 0.2% kernel / faults: 1978 minor 1800 major
  0% 2347/com.samsung.slsi.telephony.oemril: 0% user + 0% kernel / faults: 2057 minor 2320 major
  0.4% 12/rcu_preempt: 0% user + 0.4% kernel
  0.4% 84/kcompactd0: 0% user + 0.4% kernel
  0.4% 147/thermal_BIG: 0% user + 0.4% kernel
  0.4% 1069/irq/450-sec_ts: 0% user + 0.4% kernel
  0.4% 2191/com.android.networkstack.process: 0.1% user + 0.2% kernel / faults: 1844 minor 1045 major
  0% 2225/com.samsung.slsi.telephony.oem.oemrilhookservice: 0% user + 0% kernel / faults: 1892 minor 2239 major
  0% 2272/[com.android.se](http://com.android.se/): 0% user + 0% kernel / faults: 1941 minor 1992 major
  0.3% 523/sugov:6: 0% user + 0.3% kernel
  0.3% 827/twoshay: 0.3% user + 0% kernel
  0.3% 1011/dhd_rpm_state_t: 0% user + 0.3% kernel
  0% 1347/kworker/u16:2-events_unbound: 0% user + 0% kernel
  0% 3522/com.qorvo.uwb.vendorservice: 0% user + 0% kernel / faults: 1886 minor 2256 major
  0.2% 49/rcuog/4: 0% user + 0.2% kernel
  0% 1120/media.codec: 0% user + 0% kernel / faults: 1319 minor 88 major
  0.2% 151/thermal_MID: 0% user + 0.2% kernel
  0.2% 154/thermal_LITTLE: 0% user + 0.2% kernel
  0.2% 507/logd: 0.1% user + 0.1% kernel / faults: 143 minor 7 major
  0.2% 522/sugov:4: 0% user + 0.2% kernel
  0.2% 982/vendor.google.wifi_ext@1.0-service-vendor: 0.1% user + 0.1% kernel / faults: 1 minor
  0.2% 2443/com.android.launcher3: 0.1% user + 0.1% kernel / faults: 15 minor
  0.1% 13/rcuog/0: 0% user + 0.1% kernel
  0.1% 46/ksoftirqd/4: 0% user + 0.1% kernel
  0.1% 125/simpleinteracti: 0% user + 0.1% kernel
  0.1% 564/android.hardware.graphics.composer@2.4-service: 0% user + 0.1% kernel
  0% 723/tombstoned: 0% user + 0% kernel / faults: 185 minor 82 major
  0.1% 886/statsd: 0% user + 0.1% kernel / faults: 163 minor 30 major
  0.1% 949/android.hardware.sensors@2.1-service.multihal: 0% user + 0.1% kernel
  0.1% 32594/kworker/0:1-dm_bufio_cache: 0% user + 0.1% kernel
  0.1% 32680/kworker/1:0-memlat_wq: 0% user + 0.1% kernel
  0.1% 1/init: 0% user + 0% kernel / faults: 10 minor 10 major
  0.1% 243/decon0_kthread: 0% user + 0.1% kernel
  0.1% 887/netd: 0% user + 0.1% kernel / faults: 61 minor 17 major
  0% 994/audioserver: 0% user + 0% kernel / faults: 68 minor 19 major
  0.1% 1046/kworker/7:2-memlat_wq: 0% user + 0.1% kernel
  0% 1090/cameraserver: 0% user + 0% kernel / faults: 89 minor 41 major
  0% 1103/media.metrics: 0% user + 0% kernel / faults: 33 minor 10 major
  0.1% 1137/rild_exynos: 0% user + 0% kernel / faults: 1 minor 2 major
  0.1% 1331/kworker/4:0: 0% user + 0.1% kernel
  0% 1350/kworker/u16:6-events_unbound: 0% user + 0% kernel
  0.1% 1508/kworker/6:0-memlat_wq: 0% user + 0.1% kernel
  0.1% 1630/android.hardware.thermal@2.0-service.pixel: 0% user + 0.1% kernel
  0.1% 1759/android.hardware.input.processor-service: 0.1% user + 0% kernel
  0% 18997/org.thoughtcrime.securesms: 0% user + 0% kernel / faults: 8 minor
  0% 29344/com.google.android.gms.persistent: 0% user + 0% kernel / faults: 68 minor 1 major
  0.1% 32052/kworker/u17:2-kbase_pm_poweroff_wait: 0% user + 0.1% kernel
  0.1% 32632/kworker/u16:1-gpu-dvfs-control: 0% user + 0.1% kernel
  0.1% 32727/kworker/3:0-memlat_wq: 0% user + 0.1% kernel
  0% 32730/kworker/u17:0-kbase_pm_poweroff_wait: 0% user + 0% kernel
  0% 11/ksoftirqd/0: 0% user + 0% kernel
  0% 14/rcuop/0: 0% user + 0% kernel
  0% 25/ksoftirqd/1: 0% user + 0% kernel
  0% 28/rcuop/1: 0% user + 0% kernel
  0% 35/rcuop/2: 0% user + 0% kernel
  0% 39/ksoftirqd/3: 0% user + 0% kernel
  0% 42/rcuop/3: 0% user + 0% kernel
  0% 50/rcuop/4: 0% user + 0% kernel
  0% 57/rcuop/5: 0% user + 0% kernel
  0% 111/spi11: 0% user + 0% kernel
  0% 540/android.system.suspend@1.0-service: 0% user + 0% kernel
  0% 716/android.hardware.power-service.pixel-libperfmgr: 0% user + 0% kernel
  0% 783/loop25: 0% user + 0% kernel
  0% 790/loop27: 0% user + 0% kernel
  0% 909/rlsservice: 0% user + 0% kernel
  0% 1014/dhd_logtrace_th: 0% user + 0% kernel
  0% 1060/traced_probes: 0% user + 0% kernel
  0% 1292/com.google.usf.: 0% user + 0% kernel
  0% 1336/kworker/u17:1-ufs_clk_gating_0: 0% user + 0% kernel
  0% 1372/kworker/5:1-pm: 0% user + 0% kernel
  0% 2361/irq/449-dhdpcie: 0% user + 0% kernel
  0% 21529/com.mining.app.mipca: 0% user + 0% kernel / faults: 4 minor 2 major
  0% 21627/app.vanadium.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0: 0% user + 0% kernel / faults: 1 minor
  0% 24569/app.vanadium.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0: 0% user + 0% kernel / faults: 1 minor
  0% 29228/com.google.android.gms: 0% user + 0% kernel / faults: 1 major
  0% 29742/free.reddit.news: 0% user + 0% kernel / faults: 7 minor 2 major
  0% 32679/kworker/2:1-memlat_wq: 0% user + 0% kernel
39% TOTAL: 22% user + 16% kernel + 0.1% iowait + 0.3% irq + 0.3% softirq
CPU usage from 67ms to 527ms later (2023-02-13 10:46:57.012 to 2023-02-13 10:46:57.471):
  130% 13161/org.telegram.messenger: 53% user + 76% kernel / faults: 51 minor
    47% 13192/globalQueue: 15% user + 31% kernel
    34% 13161/egram.messenger: 19% user + 15% kernel
    6.3% 3345/DispatchQueuePo: 3.1% user + 3.1% kernel
    6.3% 12058/DispatchQueuePo: 3.1% user + 3.1% kernel
    6.3% 12059/DispatchQueuePo: 0% user + 6.3% kernel
    6.3% 12060/DispatchQueuePo: 3.1% user + 3.1% kernel
    6.3% 12093/DispatchQueuePo: 3.1% user + 3.1% kernel
    6.3% 22056/DispatchQueuePo: 3.1% user + 3.1% kernel
    6.3% 22057/DispatchQueuePo: 3.1% user + 3.1% kernel
    3.1% 12057/DispatchQueuePo: 0% user + 3.1% kernel
  98% 30797/com.vitorpamplona.amethyst: 98% user + 0% kernel / faults: 1783 minor
    98% 1565/[ay.damus.io/..](http://ay.damus.io/).: 98% user + 0% kernel
  55% 1512/system_server: 19% user + 35% kernel / faults: 757 minor
    44% 2180/AnrConsumer: 13% user + 30% kernel
    2.7% 1580/ActivityManager: 0% user + 2.7% kernel
    2.7% 1591/batterystats-ha: 0% user + 2.7% kernel
    2.7% 10094/binder:1512_13: 2.7% user + 0% kernel
  11% 2377/com.android.phone: 8.8% user + 2.9% kernel / faults: 243 minor
    5.9% 2377/m.android.phone: 5.9% user + 0% kernel
    2.9% 2625/binder:2377_3: 0% user + 2.9% kernel
    2.9% 2711/binder:2377_8: 2.9% user + 0% kernel
  5.8% 2329/com.shannon.imsservice: 2.9% user + 2.9% kernel / faults: 113 minor 2 major
    2.9% 2329/nnon.imsservice: 2.9% user + 0% kernel
  6.5% 20209/.ShannonImsService: 3.2% user + 3.2% kernel / faults: 12 minor
    3.2% 1503/binder:20209_F: 3.2% user + 0% kernel
  2.1% 1/init: 0% user + 2.1% kernel
  2.1% 12/rcu_preempt: 0% user + 2.1% kernel
  2.2% 49/rcuog/4: 0% user + 2.2% kernel
  2.3% 523/sugov:6: 0% user + 2.3% kernel
  2.6% 1046/kworker/7:2-memlat_wq: 0% user + 2.6% kernel
  2.6% 1137/rild_exynos: 2.6% user + 0% kernel / faults: 1 minor 2 major
  2.7% 1347/kworker/u16:2-events_unbound: 0% user + 2.7% kernel
  3.3% 28701/com.Slack: 0% user + 3.3% kernel / faults: 12 minor
40% TOTAL: 23% user + 15% kernel + 0.2% iowait + 0.2% irq + 0.2% softirq
```

**Comment by kirkawolff** [comment]
Also using graphene. This is app freeze and crash from allocating too much memory. Memory leak?

```
type: crash
osVersion: google/raven/raven:13/TQ1A.230205.002/2023021000:user/release-keys
package: com.vitorpamplona.amethyst:55
process: com.vitorpamplona.amethyst
processUptime: 88202 + 232 ms

java.lang.OutOfMemoryError: Failed to allocate a 11920 byte allocation with 3647312 free bytes and 3561KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at okio.Buffer.readByteArray(Buffer.kt:1075)
	at okio.Buffer.readString(Buffer.kt:313)
	at okio.Buffer.readUtf8(Buffer.kt:297)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by vitorpamplona** [comment]
Working on this right now. It is not a leak, just waay too much data being downloaded (specially if you are using public relays for public chats... Lots of spam)

**Comment by vitorpamplona** [comment]
This specific one has been solved. We are still watching for other out-of-memory errors and memory leaks.
