### ISSUE TITLE
Bug: App Crash

### ISSUE THREAD

**Issue by pluja** [vitorpamplona/amethyst#129]
The app keeps crashing and I can't even use it

Versio: 16.0
Device: Pixel 6a
OS: GraphenOS /Android 13

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.230205.002/2023020600:user/release-keys
package: com.vitorpamplona.amethyst:53
process: com.vitorpamplona.amethyst
processUptime: 94219 + 192 ms

java.lang.Error: can't parse hello
	at com.vitorpamplona.amethyst.service.model.ChannelCreateEvent.<init>(ChannelCreateEvent.kt:22)
	at com.vitorpamplona.amethyst.service.NostrDataSource$clientListener$1.onEvent(NostrDataSource.kt:88)
	at com.vitorpamplona.amethyst.service.relays.Client$onEvent$1.invokeSuspend(Client.kt:69)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d2df64, Dispatchers.Default]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at com.vitorpamplona.amethyst.service.model.ChannelCreateEvent.<init>(ChannelCreateEvent.kt:20)
	... 8 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 13 more

```

**Comment by vitorpamplona** [comment]
ohhh interesting.. Looks like there is an invalid ChannelCreate event saved in one of your relays. I will do some Research and see if we can ignore this error
