### ISSUE TITLE
[BUG] Tagging users causes crash when post contains content

### ISSUE THREAD

**Issue by TheSameCat2** [vitorpamplona/amethyst#326]
**Describe the bug**
Amethyst crashes when tagging users in a post, when the post contains an uploaded image.

**To Reproduce**
1. Create a new post
2. Upload an image
3. Move cursor to beginning of post
4. Press "@" and begin typing username
5. Tap user in autocomplete list.

**Expected behavior**
User should be tagged in post

**Video and Screenshots**
Stack Trace @ Crash:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vitorpamplona.amethyst.debug, PID: 5315
    java.lang.IndexOutOfBoundsException: setSpan (66 ... 97) ends beyond length 40
        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:493)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:199)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:186)
        at android.text.SpannableString.setSpan(SpannableString.java:60)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt.setSpan(SpannableExtensions.android.kt:80)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt.setColor-RPmYEkk(SpannableExtensions.android.kt:491)
        at androidx.compose.ui.text.platform.AndroidAccessibilitySpannableString_androidKt.setSpanStyle(AndroidAccessibilitySpannableString.android.kt:112)
        at androidx.compose.ui.text.platform.AndroidAccessibilitySpannableString_androidKt.toAccessibilitySpannableString(AndroidAccessibilitySpannableString.android.kt:79)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.setText(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1301)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.populateAccessibilityNodeInfoProperties(AndroidComposeViewAccessibilityDelegateCompat.android.kt:796)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:549)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:193)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$MyNodeProvider.createAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3062)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1572)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1582)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1582)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1582)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1481)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1243)
        at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:396)
        at android.view.AccessibilityInteractionController.-$$Nest$mfindAccessibilityNodeInfoByAccessibilityIdUiThread(Unknown Source:0)
        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1647)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7884)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel 6 Pro
 - Android Version [e.g. 33]: 13 (API33) - March 5, 2023 Security Update - March 1, 2023 Google Play Update
 - App Version [e.g. v0.20.3]:  0.31.0

**Bounty (in Bitcoin sats) offered for a solution**
Ack! I need to reload on Sats!

**Comment by TheSameCat2** [comment]
Looks like this might be in ClickableUserTag.kt or RichTextViewer.kt?

If I find a fix I'll open a PR. I know you're busy, and this is quite obviously an edge case.

**Comment by vitorpamplona** [comment]
It might be something on the UrlUserTagTransformation, which is used as a visual transformation to show people's names instead of their npub. There might be something wrong with the indexes there that doesn't work on Pixel 6, but works on 7.
