### ISSUE TITLE
[BUG] app crash

### ISSUE THREAD

**Issue by jlopp** [vitorpamplona/amethyst#529]
**Describe the bug**
App regularly crashes while scrolling through feed.

**To Reproduce**
Scroll a bunch through my feed.

**Expected behavior**
Not crashing.

```
type: crash
osVersion: google/raven/raven:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.vitorpamplona.amethyst:264
process: com.vitorpamplona.amethyst
processUptime: 81356 + 193 ms
installer: com.aurora.store

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
at com.vitorpamplona.amethyst.PlaybackClientController.prepareController$lambda$0(PlaybackClientController.kt:36)
at com.vitorpamplona.amethyst.PlaybackClientController.$r8$lambda$Zfe2Sr0rhzF4UjCFCVShvDccBm8(Unknown Source:0)
at com.vitorpamplona.amethyst.PlaybackClientController$$ExternalSyntheticLambda0.run(Unknown Source:4)
at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
at androidx.media3.session.MediaController.release(MediaController.java:512)
at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda82.run(Unknown Source:2)
at androidx.media3.common.util.Util.postOrRun(Util.java:662)
at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1881)
at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:96)
at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda4.run(Unknown Source:0)
at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:310)
at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda13.run(Unknown Source:4)
at androidx.media3.common.util.Util.postOrRun(Util.java:662)
at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:302)
at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:94)
at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:708)
at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(Unknown Source:14)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7940)
... 5 more
Caused by: java.lang.SecurityException: Session rejected the connection request.
... 25 more

```

**Device (please complete the following information):**
 - Phone Brand/Model: Pixel 6 Pro
 - Android Version: 13
 - App Version: v70.something

**Comment by vitorpamplona** [comment]
I do think 0.71.0 already fixes this. Basically, the app was starting faster than the background playback service. We added a few protections to not crash in this particular line.

**Comment by jlopp** [comment]
Gotcha; I have a new one that's similar that I'll file now.
