### ISSUE TITLE
[BUG] out of memory crash

### ISSUE THREAD

**Issue by jlopp** [vitorpamplona/amethyst#530]
**Describe the bug**
App regularly crashes while scrolling through feed.

**To Reproduce**
Scroll a bunch through my feed.

**Expected behavior**
Not crashing.

```
type: crash
osVersion: google/raven/raven:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.vitorpamplona.amethyst:266
process: com.vitorpamplona.amethyst
processUptime: 45392 + 459 ms
installer: com.aurora.store

java.lang.OutOfMemoryError: Failed to allocate a 4952 byte allocation with 734496 free bytes and 717KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
at java.util.Arrays.copyOf(Arrays.java:3645)
at java.util.Arrays.copyOf(Arrays.java:3614)
at java.util.ArrayList.grow(ArrayList.java:275)
at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
at java.util.ArrayList.add(ArrayList.java:467)
at com.vitorpamplona.amethyst.ui.screen.FeedViewModel.refreshFromOldState(FeedViewModel.kt:350)
at com.vitorpamplona.amethyst.ui.screen.FeedViewModel$invalidateInsertData$1.invokeSuspend(FeedViewModel.kt:315)
at com.vitorpamplona.amethyst.ui.screen.FeedViewModel$invalidateInsertData$1.invoke(Unknown Source:8)
at com.vitorpamplona.amethyst.ui.screen.FeedViewModel$invalidateInsertData$1.invoke(Unknown Source:4)
at com.vitorpamplona.amethyst.ui.components.BundledInsert$invalidateList$1.invokeSuspend(BundledUpdate.kt:77)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@24e681e, Dispatchers.IO]

```

**Device (please complete the following information):**
 - Phone Brand/Model: Pixel 6 Pro
 - Android Version: 13
 - App Version: v0.71.0

**Comment by KotlinGeekDev** [comment]
Please @jlopp does still occur on the latest version?

**Comment by jlopp** [comment]
Seems to be fixed; I can't get the app to crash any more.
